config/routes.rb
Rails.application.routes.draw do
  root 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [ :new, :create, :delete ]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :cocktail, uniqueness: { scope: :ingredient }
  validates :description, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  # GET /cocktails
  def index
    @cocktails = Cocktail.all
  end

  # GET /cocktails/1
  def show
    @dose = Dose.new
  end

  # GET /cocktails/new
  def new
    @cocktail = Cocktail.new
  end

  # # GET /cocktails/1/edit
  # def edit
  # end

  # POST /cocktails
  def create
    @cocktail = Cocktail.new(cocktail_params)

      if @cocktail.save
        redirect_to @cocktail
      else
        render :new
      end
  end

  # PATCH/PUT /cocktails/1

  # def update
  #   respond_to do |format|
  #     if @cocktail.update(cocktail_params)
  #       redirect_to @cocktail, notice: 'Cocktail was successfully updated.'
  #     else
  #       render :new
  #     end
  #   end
  # end

  # DELETE /cocktails/1
  def destroy
    @cocktail.destroy
    redirect_to cocktails_url, notice: 'Cocktail was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cocktail_params
      params.require(:cocktail).permit(:name)
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: [:show, :edit, :update, :destroy]

  # GET /doses
  # def index
  #   @doses = Dose.all
  # end

  # GET /doses/1
  def show
  end

  # GET /doses/new
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  # # GET /doses/1/edit
  # def edit
  # end

  # POST /doses
  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail

      if @dose.save
        redirect_to @cocktail, notice: 'Dose was successfully created.' 
      else
        render :new
      end
  end

  # DELETE /doses/1
  def destroy
    @dose.destroy
    redirect_to cocktail_url(@cocktail), notice: 'Dose was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dose
      @dose = Dose.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dose_params
      params.require(:dose).permit(:description, :ingredient_id)
    end
end

app/controllers/ingredients_controller.rb
# class IngredientsController < ApplicationController
#   before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

#   # GET /ingredients
#   # GET /ingredients.json
#   def index
#     @ingredients = Ingredient.all
#   end

#   # GET /ingredients/1
#   # GET /ingredients/1.json
#   def show
#   end

#   # GET /ingredients/new
#   def new
#     @ingredient = Ingredient.new
#   end

#   # GET /ingredients/1/edit
#   def edit
#   end

#   # POST /ingredients
#   # POST /ingredients.json
#   def create
#     @ingredient = Ingredient.new(ingredient_params)

#     respond_to do |format|
#       if @ingredient.save
#         format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
#         format.json { render :show, status: :created, location: @ingredient }
#       else
#         format.html { render :new }
#         format.json { render json: @ingredient.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # PATCH/PUT /ingredients/1
#   # PATCH/PUT /ingredients/1.json
#   def update
#     respond_to do |format|
#       if @ingredient.update(ingredient_params)
#         format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
#         format.json { render :show, status: :ok, location: @ingredient }
#       else
#         format.html { render :edit }
#         format.json { render json: @ingredient.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # DELETE /ingredients/1
#   # DELETE /ingredients/1.json
#   def destroy
#     @ingredient.destroy
#     respond_to do |format|
#       format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
#       format.json { head :no_content }
#     end
#   end

#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_ingredient
#       @ingredient = Ingredient.find(params[:id])
#     end

#     # Only allow a list of trusted parameters through.
#     def ingredient_params
#       params.require(:ingredient).permit(:name)
#     end
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%# <%= f.input :url %>
  </div>


  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Editing Cocktail</h1>

<div class="cocktail-form">
<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Back to Recipe', @cocktail %> |
<%= link_to 'All Cocktails', cocktails_path %>
</div>

app/views/cocktails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cocktails</h1>

  <div class="row p-4">
    <% @cocktails.each do |cocktail| %>
    <div class="my_card col-6 col-md-4">
      <div class="inner">
        <p class="name text-center"><%= cocktail.name %></p>
    
        <div class="btn btn-outline-success"><%= link_to 'View', cocktail %></div>
      </div>
    </div>
    <% end %>
  </div>

<br>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>
<div class="cocktail-form">
  <p>give your cocktail a nice juicy name</p>
  <%= render 'form', cocktail: @cocktail %>
  <%= link_to 'Back', cocktails_path(@cocktail) %>
</div>

app/views/cocktails/show.html.erb
<div class="cocktail-form">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cocktail.name %>
</p>
<p>
  <strong>Ingredients:</strong>
</p>

  <% @cocktail.doses.each do |i| %>
  <p><%= i.ingredient.name %>: <%= i.description %></p>
  <% end %>
  
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <%= f.input :description %>
    <%= f.association :ingredient %>

    <%= f.button :submit %> 
    <div></div>
    <div class="btn btn-outline-success"><%= link_to 'Delete Recipe', @cocktail, method: :delete, data: { confirm: 'Are you sure? This cocktail recipe will be deleted forever.' } %></div>
<% end %>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.association :cocktail, :as => :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/doses/edit.html.erb
<h1>Editing Dose</h1>

<div class="cocktail-form">
<%= render 'form', dose: @dose %>

<%= link_to 'Show', @dose %> |
<%= link_to 'Back', doses_path %>

</div>

app/views/doses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doses</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Cocktail</th>
      <th>Ingredient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doses.each do |dose| %>
      <tr>
        <td><%= dose.description %></td>
        <td><%= dose.cocktail %></td>
        <td><%= dose.ingredient %></td>
        <td><%= link_to 'Show', dose %></td>
        <td><%= link_to 'Edit', edit_dose_path(dose) %></td>
        <td><%= link_to 'Destroy', dose, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/doses/new.html.erb
<h1>New Dose</h1>

<div class="cocktail-form">
<%= render 'form', dose: @dose %>

<%= link_to 'Back', cocktail_path(@cocktail) %>
</div>

app/views/doses/show.html.erb
<p id="notice"><%= notice %></p>

<div class="cocktail-form">
<p>
  <strong>Description:</strong>
  <%= @dose.description %>
</p>

<p>
  <strong>Cocktail:</strong>
  <%= @dose.cocktail %>
</p>

<p>
  <strong>Ingredient:</strong>
  <%= @dose.ingredient %>
</p>

<%= link_to 'Edit', edit_dose_path(@dose) %> |
<%= link_to 'Back', doses_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>  

    <%= render 'shared/navbar' %>
    
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light position-sticky fixed-top">
  <%# <i class="fas fa-cocktail"></i> %>
  <h1><%= link_to icon("fas", "cocktail"), cocktails_path, class: "strong" %></h1>
  <%= link_to "Create a Cocktail", new_cocktail_path, class: "btn btn-outline-success my-2 my-sm-0 badge-pill" %> 
</nav>